### ISSUE TITLE
Add screenshot

### ISSUE THREAD

**Issue by jenstornell** [ivinteractive/kirbycms-redirects#3]
Maybe this one

![image](https://cloud.githubusercontent.com/assets/927011/24247277/5569c9ae-0fcb-11e7-93ed-13164fb0cce0.png)

**Comment by ivi-admin** [comment]
That's added! https://github.com/ivinteractive/kirbycms-redirects/commit/5e3b285caf9a0e7ba8a15cf7bbf620a62f5bf575
